---
global:
  tt_include: config.d
cases:
- tt_members: Alumno 1
  webserver_ip: 192.168.122.254
  webserver_username: alumno1
  webserver_password: secret1
- tt_members: Alumno 2
  webserver_ip: 192.168.122.108
  webserver_username: alumno2
  webserver_password: secret2
